### PR TITLE
Fix snapshots

### LINKED ISSUE #43: snapshots seem not to work
this test (simplified for this issue):

``` js
test('iterator create snapshot correctly', function (t) {
    db.put('foobatch1', 'bar1', function(err){
      t.error(err)
      var iterator = db.iterator()
      db.del('foobatch1', function () {
        iterator.next(function (err, key, value) {
          t.notOk(err, 'no error')
          t.ok(key, 'got a key')
          t.equal(key.toString(), 'foobatch1', 'correct key')
          t.equal(value.toString(), 'bar1', 'correct value')
          iterator.end(t.end.bind(t))
        })
      })
    })
  })
```

is failing:

```
# iterator create snapshot correctly
default_stream.js:27 ok 419 no error
default_stream.js:27 not ok 420 got a key
default_stream.js:27   ---
default_stream.js:27     operator: ok
default_stream.js:27     expected: true
default_stream.js:27     actual:   undefined
default_stream.js:27     at: Test.assert (http://localhost:9966/test.js:12977:17)
default_stream.js:27   ...
iterator-test.js:467 Uncaught TypeError: Cannot read property 'toString' of undefined
```

@maxogden do you know what's going on here?

### LINKED ISSUE #61: Get current tests passing
Without updating anything yet.

It doesn't pass the iterator snapshot test currently, because `level.js` creates the IDB cursor lazily (on `next`). It should create it in the Iterator constructor instead.

### LINKED ISSUE #63: Add a cache to Iterator
From https://github.com/Level/level.js/issues/60#issuecomment-365379574:

> Iterators should by default keep reading from the underlying IDB cursor, to fulfill the snapshot guarantee

- [ ] Have the IDB cursor fill a cache (similar to how leveldown works with highWaterMark)
- [ ] Have `Iterator.prototype._next()` read from the cache.

This cleanly separates the two mechanisms (IDB pushes, Iterator pulls).

### PR DESCRIPTION
**Pull request by vweevers**
Closes #63, closes #61, closes #43, also tackles #42, supersedes #51.

At a later time, we can add an option that favors backpressure over snapshot guarantees, by reading lazily from multiple successive cursors.

### CODE REVIEW

**Comment by vweevers** [comment]
@ralphtheninja I just realized: maybe we should work in a v3 branch first?

**Comment by ralphtheninja** [comment]
> @ralphtheninja I just realized: maybe we should work in a v3 branch first?

I have no strong opinions about it since master will become `3.0.0`. But if you want to do it, lets do it.

File: iterator.js [hunk 1]
```diff
@@ -40,33 +59,56 @@ Iterator.prototype.createIterator = function() {
...
+  if (this._callback) {
+    this._next(this._callback)
+    this._callback = null
+  }
 }
 
+// TODO: use setImmediate (see memdown)
 Iterator.prototype._next = function (callback) {
+  // TODO: can remove this after upgrading abstract-leveldown
   if (!callback) return new Error('next() requires a callback argument')
```
Comment (ralphtheninja) [inline iterator.js]: Returning an error looks a bit odd, shouldn't it throw?

**Comment by vweevers** [comment]
Nah it's fine :)

File: iterator.js (hunk 1 above)
Comment (vweevers) [reply iterator.js]: Woa, dunno why I missed that 😄
