### PR TITLE
Remove ArrayBuffer in favor of Buffer

### LINKED ISSUE #34: Array Buffers
If I try to put array buffer into a db that has valueEncoding set to 'binary' I get an error about 

```
message: "value cannot be an empty ArrayBuffer"
name: "WriteError"
```

as far as I can tell this is due to it being improperly turned into a Uint8 at some point, I managed to trace it to [here](https://github.com/rvagg/node-levelup/blob/master/lib/util.js#L35) where the array Buffer failed the Buffer.isBuffer test, but then when new Buffer(ArrayBuffer) is called it uses ArrayBuffer.prototype.length instead of ArrayBuffer.prototype.byteLength, so I'll likely have to open an issue there as well

### PR DESCRIPTION
**Pull request by vweevers**
Closes #34.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -159,16 +151,3 @@ Level.destroy = function (db, callback) {
     callback(err)
   }
 }
-
-var checkKeyValue = Level.prototype._checkKeyValue = function (obj, type) {
```
Comment (vweevers) [inline index.js]: This method was dead (it's now called `_checkKey` in `abstract-leveldown`), but without the need for Array Buffers, the default works fine. Except for https://github.com/Level/abstract-leveldown/issues/230, but that's hardly a priority.
